import {
  AlertPage,
  AvatarPage,
  BadgePage,
  BreadcrumbPage,
  ButtonPage,
  CardBasicPage,
  CardStatisticPage,
  CheckboxPage,
  ChipPage,
  ColorPickerPage,
  CollapsiblePage,
  Dashboard,
  DatePickerPage,
  DrawerPage,
  ExampleTablePage,
  ExampleTemplateInvoice,
  FileInputPage,
  ListPage,
  ModalPage,
  MonthPickerPage,
  PaginationPage,
  PopoverPage,
  RadioPage,
  SelectPage,
  SwitchPage,
  TablePage,
  TabsPage,
  TextAreaPage,
  TextFieldPage,
  TimelinePage,
  TooltipPage,
  MapPage,
  ExampleTemplateKuitansi,
  CalendarPage,
  CarouselPage,
  SweetAlertPage,
  // ReconnaissancePage,
  // VulneranalysisPage,
} from "@/template";
// import { FaWolfPackBattalion } from "react-icons/fa";
// import { GiBrokenShield } from "react-icons/gi";
import {
  PiCalendarDots,
  PiCards,
  PiHouseLine,
  PiIdentificationCard,
  PiMapTrifold,
  PiPerspective,
  PiTable,
  PiTextbox
} from "react-icons/pi";

// Adjust the SubMenu interface to not have a nested sub property
interface SubMenu {
  path: string;
  element: JSX.Element;
  icon?: JSX.Element | null;
  name?: string | JSX.Element | null;
  title?: string;
  sub?: [];
  menuLink?: string;
}

// MenuItem interface with sub as an array of SubMenu
interface MenuItem {
  path?: string;
  element?: JSX.Element | null;
  icon?: JSX.Element;
  name?: string | JSX.Element | undefined;
  title?: string;
  sub?: SubMenu[];
  label?: string;
  menuLink?: string;
  iconActive?: string;
}

export const menu: MenuItem[] = [
  {
    icon: <PiHouseLine />,
    path: "/",
    name: "dashboard",
    title: "Dashboard",
    element: <Dashboard />,
    sub: [],
  },
  // {
  //   icon: <FaWolfPackBattalion />,
  //   path: "/reconnaissance",
  //   name: "reconnaissance",
  //   title: "Reconnaissance",
  //   element: <ReconnaissancePage />,
  //   sub: [],
  // },
  // {
  //   icon: <GiBrokenShield />,
  //   path: "/vulneranalysis",
  //   name: "vulneranalysis",
  //   title: "Vulneranalysis",
  //   element: <VulneranalysisPage />,
  //   sub: [],
  // },
  {
    label: "UI ELEMENTS",
  },
  {
    icon: <PiCards />,
    path: "components",
    name: "components",
    title: "Components",
    element: null,
    sub: [
      {
        icon: null,
        path: "/ui-elements/components/alert",
        name: "alert",
        title: "Alert",
        element: <AlertPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/ui-elements/components/avatar",
        name: "avatar",
        title: "Avatar",
        element: <AvatarPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/ui-elements/components/badge",
        name: "badge",
        title: "Badge",
        element: <BadgePage />,
        sub: [],
      },
      {
        icon: null,
        path: "/ui-elements/components/breadcrumb",
        name: "breadcrumb",
        title: "Breadcrumb",
        element: <BreadcrumbPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/ui-elements/components/button",
        name: "button",
        title: "Button",
        element: <ButtonPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/ui-elements/components/carousel",
        name: "carousel",
        title: "Carousel",
        element: <CarouselPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/ui-elements/components/chip",
        name: "chip",
        title: "Chip",
        element: <ChipPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/ui-elements/components/collapsible",
        name: "collapsible",
        title: "Collapsible",
        element: <CollapsiblePage />,
        sub: [],
      },
      {
        icon: null,
        path: "/ui-elements/components/drawer",
        name: "drawer",
        title: "Drawer",
        element: <DrawerPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/ui-elements/components/list",
        name: "list",
        title: "List",
        element: <ListPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/ui-elements/components/modal",
        name: "modal",
        title: "Modal",
        element: <ModalPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/ui-elements/components/pagination",
        name: "pagination",
        title: "Pagination",
        element: <PaginationPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/ui-elements/components/popover",
        name: "popover",
        title: "Popover",
        element: <PopoverPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/ui-elements/components/sweetalert",
        name: "sweetalert",
        title: "SweetAlert",
        element: <SweetAlertPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/ui-elements/components/tabs",
        name: "tabs",
        title: "Tabs",
        element: <TabsPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/ui-elements/components/tooltip",
        name: "tooltip",
        title: "Tooltip",
        element: <TooltipPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/ui-elements/components/timeline",
        name: "timeline",
        title: "Timeline",
        element: <TimelinePage />,
        sub: [],
      },
    ],
  },
  {
    icon: <PiIdentificationCard />,
    path: "cards",
    name: "cards",
    title: "Cards",
    element: null,
    sub: [
      {
        icon: null,
        path: "/ui-elements/cards/basics",
        name: "basics",
        title: "Basics",
        element: <CardBasicPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/ui-elements/cards/statistics",
        name: "statistics",
        title: "Statistics",
        element: <CardStatisticPage />,
        sub: [],
      },
    ],
  },
  {
    icon: <PiCalendarDots />,
    path: "/calendar",
    name: "calendar",
    title: "Calendar",
    element: <CalendarPage />,
    sub: [],
  },
  {
    icon: <PiMapTrifold />,
    path: "/maps",
    name: "maps",
    title: "Maps",
    element: <MapPage />,
    sub: [],
  },
  {
    label: "FORMS & TABLES",
  },
  {
    icon: <PiTextbox />,
    path: "forms",
    name: "forms",
    title: "Forms",
    element: null,
    sub: [
      {
        icon: null,
        path: "/form-tables/forms/checkbox",
        name: "checkbox",
        title: "Checkbox",
        element: <CheckboxPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/form-tables/forms/color-picker",
        name: "color-picker",
        title: "Color Picker",
        element: <ColorPickerPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/form-tables/forms/date-picker",
        name: "date-picker",
        title: "Date Picker",
        element: <DatePickerPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/form-tables/forms/file-input",
        name: "file-input",
        title: "File Input",
        element: <FileInputPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/form-tables/forms/month-picker",
        name: "month-picker",
        title: "Month Picker",
        element: <MonthPickerPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/form-tables/forms/radio",
        name: "radio",
        title: "Radio",
        element: <RadioPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/form-tables/forms/select",
        name: "select",
        title: "Select",
        element: <SelectPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/form-tables/forms/switch",
        name: "switch",
        title: "Switch",
        element: <SwitchPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/form-tables/forms/textarea",
        name: "textarea",
        title: "Text Area",
        element: <TextAreaPage />,
        sub: [],
      },
      {
        icon: null,
        path: "/form-tables/forms/textfield",
        name: "textfield",
        title: "Text Field",
        element: <TextFieldPage />,
        sub: [],
      },
    ],
  },
  {
    icon: <PiTable />,
    path: "tables",
    name: "tables",
    title: "Tables",
    element: null,
    sub: [
      {
        icon: null,
        path: "/form-tables/tables/table",
        name: "table",
        title: "Table",
        element: <TablePage />,
        sub: [],
      },
    ],
  },
  {
    label: "EXAMPLES",
  },
  {
    icon: <PiPerspective />,
    path: "examples",
    name: "examples",
    title: "Examples",
    element: null,
    sub: [
      {
        icon: null,
        path: "/examples/examples/table",
        name: "table",
        title: "Table",
        element: <ExampleTablePage />,
        sub: [],
      },
      {
        icon: null,
        path: "/examples/examples/invoice",
        name: "invoice",
        title: "Invoice",
        element: <ExampleTemplateInvoice />,
        sub: [],
      },
      {
        icon: null,
        path: "/examples/examples/kuitansi",
        name: "kuitansi",
        title: "Kuitansi",
        element: <ExampleTemplateKuitansi />,
        sub: [],
      },
    ],
  },
];
